In [11]:
import pandas as pd
import pyarrow.dataset as ds

dataset = ds.dataset('/home/wsl/data/movies/dailyboxoffice', format='parquet', partitioning="hive")
df = dataset.to_table().to_pandas()

df.to_parquet("~/temp/movie.parquet")

In [12]:
df.columns

Index(['rnum', 'rank', 'rankInten', 'rankOldAndNew', 'movieCd', 'movieNm',
       'openDt', 'salesAmt', 'salesShare', 'salesInten', 'salesChange',
       'salesAcc', 'audiCnt', 'audiInten', 'audiChange', 'audiAcc', 'scrnCnt',
       'showCnt', 'dt', 'multiMovieYn', 'repNationCd'],
      dtype='object')

In [13]:
df

,rnum,rank,rankInten,rankOldAndNew,movieCd,movieNm,openDt,salesAmt,salesShare,salesInten,...,salesAcc,audiCnt,audiInten,audiChange,audiAcc,scrnCnt,showCnt,dt,multiMovieYn,repNationCd
0,1,1,0,OLD,20203702,노량: 죽음의 바다,2023-12-20,2893509165,38.8,-686119312,...,36926118105,290717,-59184,-16.9,3728850,1706,5793,20240101,None,None
1,2,2,0,OLD,20212866,서울의 봄,2023-11-22,2666429137,35.8,-649456909,...,118016920547,262422,-64054,-19.6,12117201,1614,5444,20240101,None,None
2,3,3,0,OLD,20236146,신차원! 짱구는 못말려 더 무비 초능력 대결전 ~날아라 수제김밥~,2023-12-22,565417320,7.6,-69888800,...,6071745009,58239,-6751,-10.4,626508,834,1671,20240101,None,None
3,4,4,0,OLD,20235735,아쿠아맨과 로스트 킹덤,2023-12-20,507984981,6.8,-156026099,...,7967584753,49368,-14686,-22.9,772354,832,1611,20240101,None,None
4,5,5,0,OLD,20235596,트롤: 밴드 투게더,2023-12-20,273538754,3.7,-16945147,...,3383181955,28988,-1952,-6.3,365927,660,981,20240101,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18295,6,6,-2,OLD,20247430,퍼스트레이디,2024-12-12,4931800,0.1,-5293100,...,773313180,584,-538,-48.0,80010,53,67,20241231,None,K
18296,7,7,0,NEW,20241180,"괜찮아, 앨리스",2024-11-13,3863000,0.1,3863000,...,191214000,440,440,100.0,21361,2,2,20241231,None,K
18297,8,8,-1,OLD,20225184,히든페이스,2024-11-20,4020200,0.1,-2018100,...,9591875140,404,-207,-33.9,1012014,33,38,20241231,None,K
18298,9,9,-1,OLD,20212352,1승,2024-12-04,1869300,0.1,-2163700,...,2813553530,267,-233,-46.6,322017,5,5,20241231,None,K
18299,10,10,2,OLD,20248129,엘리자벳: 더 뮤지컬 라이브,2024-10-16,4651000,0.1,88000,...,1198446400,196,1,0.5,48984,11,11,20241231,None,K